Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/User.py", line 6, in register
    return "Done: {} is the last id created".format(self.model(self.get_request_parameters()).save())
  File "/home/pcc/uniwallet/framework/Controller.py", line 38, in model
    model_instance = getattr(importlib.import_module("modules.{}.{}".format(self.request.module, model_name)), model_name)(self.get_db_config(), data)
  File "/home/pcc/uniwallet/framework/Controller.py", line 27, in get_db_config
    return getattr(importlib.import_module("modules.{}.db.config".format(self.request.module)), "config")()
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'modules.backend.db.config'

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/User.py", line 6, in register
    return "Done: {} is the last id created".format(self.model(self.get_request_parameters()).save())
  File "/home/pcc/uniwallet/framework/Controller.py", line 38, in model
    model_instance = getattr(importlib.import_module("modules.{}.{}".format(self.request.module, model_name)), model_name)(self.get_db_config(), data)
  File "/home/pcc/uniwallet/framework/Model.py", line 8, in __init__
    self.db = std.Database(db_config)
  File "/home/pcc/uniwallet/framework/Database.py", line 8, in __init__
    self.conn = mysql.connector.connect(**config)
  File "/usr/lib/python3/dist-packages/mysql/connector/__init__.py", line 162, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 454, in connect
    self._open_connection()
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 421, in _open_connection
    self._ssl)
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 204, in _do_auth
    self._auth_switch_request(username, password)
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 240, in _auth_switch_request
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
  File "/home/pcc/uniwallet/framework/Model.py", line 63, in save
    conn, cursor = self.run_standard_query("create", self.get_attributes())
  File "/home/pcc/uniwallet/framework/Model.py", line 52, in run_standard_query
    cursor = self.db.execute(self.db.build_query(script_name, self.get_table_name(), attributes.keys()), attributes)
  File "/home/pcc/uniwallet/framework/Database.py", line 37, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'Uniwallet.Transactions' doesn't exist

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
  File "/home/pcc/uniwallet/framework/Model.py", line 63, in save
    conn, cursor = self.run_standard_query("create", self.get_attributes())
  File "/home/pcc/uniwallet/framework/Model.py", line 52, in run_standard_query
    cursor = self.db.execute(self.db.build_query(script_name, self.get_table_name(), attributes.keys()), attributes)
  File "/home/pcc/uniwallet/framework/Database.py", line 37, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'value' at row 1

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
  File "/home/pcc/uniwallet/framework/Model.py", line 63, in save
    conn, cursor = self.run_standard_query("create", self.get_attributes())
  File "/home/pcc/uniwallet/framework/Model.py", line 52, in run_standard_query
    cursor = self.db.execute(self.db.build_query(script_name, self.get_table_name(), attributes.keys()), attributes)
  File "/home/pcc/uniwallet/framework/Database.py", line 37, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'value' at row 1

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
  File "/home/pcc/uniwallet/framework/Model.py", line 63, in save
    conn, cursor = self.run_standard_query("create", self.get_attributes())
  File "/home/pcc/uniwallet/framework/Model.py", line 52, in run_standard_query
    cursor = self.db.execute(self.db.build_query(script_name, self.get_table_name(), attributes.keys()), attributes)
  File "/home/pcc/uniwallet/framework/Database.py", line 37, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'value' at row 1

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
  File "/home/pcc/uniwallet/framework/Model.py", line 63, in save
    conn, cursor = self.run_standard_query("create", self.get_attributes())
  File "/home/pcc/uniwallet/framework/Model.py", line 52, in run_standard_query
    cursor = self.db.execute(self.db.build_query(script_name, self.get_table_name(), attributes.keys()), attributes)
  File "/home/pcc/uniwallet/framework/Database.py", line 37, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'value' at row 1

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
AttributeError: 'dict' object has no attribute 'close'

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
AttributeError: 'dict' object has no attribute 'close'

Traceback (most recent call last):
  File "/home/pcc/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/pcc/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/pcc/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/pcc/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/pcc/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/pcc/uniwallet/modules/backend/controllers/Transaction.py", line 6, in save
    self.model(self.get_request_parameters()).save().close()
AttributeError: 'dict' object has no attribute 'close'

